from pathlib import Path
from typing import Any

from plugins.registry import run_plugins
from template_registry.resolver import load_manifest


BASE_DIR = Path(__file__).resolve().parent
GENERATED_DIR = BASE_DIR / "generated"


def validate_variables(
    manifest: dict[str, Any],
    variables: dict[str, Any],
) -> tuple[bool, list[str]]:
    errors: list[str] = []

    for variable in manifest.get("variables", []):
        name = variable["name"]

        if variable.get("required") and name not in variables:
            errors.append(f"Missing variable: {name}")

    return len(errors) == 0, errors


def generate_project(
    manifest_path: str,
    variables: dict[str, Any],
) -> Path:
    manifest = load_manifest(manifest_path)

    context = {
        "manifest": manifest,
        "variables": variables,
    }

    context = run_plugins("before_generate", context)

    valid, errors = validate_variables(
        context["manifest"],
        context["variables"],
    )

    if not valid:
        raise ValueError("\n".join(errors))

    project_name = context["variables"]["PROJECT_NAME"]

    project_dir = GENERATED_DIR / project_name
    project_dir.mkdir(parents=True, exist_ok=True)

    readme_path = project_dir / "README.md"

    content = f"# {project_name}\n\nGenerated by Forge AI\n"

    readme_path.write_text(content, encoding="utf-8")

    context["project_dir"] = project_dir

    run_plugins("after_generate", context)

    return project_dir